# Generated by Django 5.2.1 on 2025-05-14 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='posts')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nb_votes', models.IntegerField(default=0)),
                ('category', models.CharField(choices=[('route', 'Route endommagée'), ('electricite', 'Panne électrique'), ('dechets', 'Déchets non collectés'), ('autre', 'Autre')], default='autre', max_length=20)),
                ('status', models.CharField(choices=[('attente', 'En attente'), ('encours', 'En cours'), ('resolu', 'Résolu')], default='attente', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.BooleanField(default=True)),
            ],
        ),
    ]
