# Generated by Django 5.2.1 on 2025-05-14 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('route', 'Route endommagée'), ('electricite', 'Panne électrique'), ('dechets', 'Déchets non collectés'), ('autre', 'Autre')], default='autre', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('attente', 'En attente'), ('encours', 'En cours'), ('resolu', 'Résolu')], default='attente', max_length=20),
        ),
    ]
