# Generated by Django 5.2.1 on 2025-05-15 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0003_alter_post_status_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('attente', 'En attente'), ('encours', 'En cours'), ('resolu', 'Résolu')], default='attente', max_length=20),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
