# Generated by Django 5.2.1 on 2025-05-14 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0004_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('route', 'Route endommagée'), ('electricite', 'Panne électrique'), ('dechets', 'Déchets non collectés'), ('environnement', 'Environnement'), ('infrastructure', 'Infrastructure'), ('securite', 'Sécurité'), ('autre', 'Autre')], default='autre', max_length=20),
        ),
    ]
